import { Event } from './types';

export const DUMMY_HACKATHONS: Event[] = [
  {
    id: 101,
    title: 'AI Future Hack',
    description: 'A hackathon focused on the future of Artificial Intelligence. Build innovative projects using the latest AI/ML technologies. Detailed description about the hackathon, its goals, and what participants can expect.',
    blurb: 'Shape the future of AI in this exciting weekend-long hackathon.',
    url: 'https://example.com/ai-future-hack',
    location: 'San Francisco, CA & Remote',
    date: 'Oct 26-28, 2024',
    imageUrl: 'https://picsum.photos/seed/101/600/400',
    provider: 'MLH',
    requirements: 'Participants should have some programming experience. Familiarity with Python and popular AI/ML frameworks like TensorFlow or PyTorch is recommended but not required. All skill levels are welcome.',
    judges: '<ul><li>Dr. Eva Core, Lead AI Researcher at GenAI Corp</li><li>Mark Vector, CTO of Innovate AI</li><li>Dr. Ada Neuron, Professor of Computer Science at Tech University</li></ul>',
    judgingCriteria: '<p>Projects will be judged on innovation, technical complexity, user experience, and potential impact. Bonus points for projects that use the sponsor APIs.</p>',
    type: 'HACKATHON',
    scrappedAt: new Date().toISOString(),
  },
  {
    id: 102,
    title: 'Web3 Wizards',
    description: 'Dive into the decentralized world with our Web3 hackathon. Build dApps, explore blockchain technology, and compete for amazing prizes.',
    blurb: 'Build the next generation of decentralized applications.',
    url: 'https://example.com/web3-wizards',
    location: 'Remote',
    date: 'Nov 1-3, 2024',
    imageUrl: 'https://picsum.photos/seed/102/600/400',
    provider: 'DEVPOST',
    requirements: 'Familiarity with blockchain concepts and smart contract development (e.g., Solidity) is helpful. Bring your ideas and willingness to learn.',
    judges: '<ul><li>Satoshi Nakamoto (Anonymous)</li><li>Vitalik Buterin (Guest Judge)</li></ul>',
    judgingCriteria: '<p>Decentralization, novelty of the idea, smart contract security, and user interface will be the main criteria.</p>',
    type: 'HACKATHON',
    scrappedAt: new Date().toISOString(),
  },
  {
    id: 103,
    title: 'Sustainable Tech Challenge',
    description: 'Use your tech skills to create solutions for a more sustainable future. This hackathon is for those passionate about environmental and social change.',
    blurb: 'Code for a cause and build solutions for a greener planet.',
    url: 'https://example.com/sustainable-tech',
    location: 'New York, NY',
    date: 'Dec 5-7, 2024',
    imageUrl: 'https://picsum.photos/seed/103/600/400',
    provider: 'MLH',
    requirements: 'No specific tech skills required. We are looking for diverse teams with a passion for sustainability.',
    judges: '<ul><li>Greta Thunberg (Activist)</li><li>Elon Musk (Engineer)</li></ul>',
    judgingCriteria: '<p>Impact on sustainability goals, feasibility, innovation, and presentation quality.</p>',
    type: 'HACKATHON',
    scrappedAt: new Date().toISOString(),
  },
];

export const DUMMY_CERTIFICATES: Event[] = [
  {
    id: 201,
    title: 'Google AI Essentials',
    description: 'Get a foundational understanding of AI and machine learning from Google experts. This certificate covers key concepts and practical applications.',
    blurb: 'Kickstart your AI journey with this foundational certificate from Google.',
    url: 'https://www.coursera.org/google-ai-essentials',
    location: 'Online',
    date: 'Self-paced',
    imageUrl: 'https://picsum.photos/seed/201/600/400',
    provider: 'Coursera',
    requirements: 'No prior experience required.',
    judges: null,
    judgingCriteria: null,
    type: 'CERTIFICATE',
    scrappedAt: new Date().toISOString(),
  },
  {
    id: 202,
    title: 'AWS Certified Cloud Practitioner',
    description: 'Validate your cloud fluency with this entry-level certification from Amazon Web Services. Learn the AWS cloud, its services, and its terminology.',
    blurb: 'The perfect starting point for a career in cloud computing.',
    url: 'https://aws.amazon.com/certification/certified-cloud-practitioner/',
    location: 'Online',
    date: 'Exam-based',
    imageUrl: 'https://picsum.photos/seed/202/600/400',
    provider: 'DEVPOST', // This is a placeholder
    requirements: 'Basic understanding of IT services and their uses in the AWS Cloud platform.',
    judges: null,
    judgingCriteria: null,
    type: 'CERTIFICATE',
    scrappedAt: new Date().toISOString(),
  },
   {
    id: 203,
    title: 'The Complete Web Development Bootcamp',
    description: 'Become a full-stack web developer with just one course. HTML, CSS, Javascript, Node, React, MongoDB, Web3 and DApps.',
    blurb: 'Learn to code and become a web developer in 2024 with this comprehensive bootcamp.',
    url: 'https://www.udemy.com/course/the-complete-web-development-bootcamp/',
    location: 'Online',
    date: 'Self-paced',
    imageUrl: 'https://picsum.photos/seed/203/600/400',
    provider: 'Udemy',
    requirements: 'No programming experience needed. You will learn everything from scratch.',
    judges: null,
    judgingCriteria: null,
    type: 'CERTIFICATE',
    scrappedAt: new Date().toISOString(),
  },
];
